### ISSUE TITLE
what happens when a variable and a term have the same name ?

### ISSUE THREAD

**Issue by Lakedaemon** [digama0/mm0#12]
in peano.mm0 (and peano_hex.mm0)

ch is a term
term ch: hex > hex > char;

but also a variable like in 
axiom ax_2 (ph ps ch: wff): $ (ph -> ps -> ch) -> (ph -> ps) -> ph -> ch $;

Does this esoteric relation : 
expression(max) <- VAR                             (if VAR is a variable in scope)
mean that we should interpret ch like a var over a term constructor, whenever we have 
to parse from primary ? (not in an operator position)

By the way, though I have tried really hard (as well as guessing a lot and trying to put myself in your shoes),  I do not really understand most of this stuff (especially the part about notation litterals): 

expression(p1) <- expression(p2)                   (if p1 < p2)
expression(max) <- '(' expression(0) ')'
expression(max) <- VAR                             (if VAR is a variable in scope)
expression(1024) <- FUNC expression(max){n}        (if FUNC is an n-ary term constructor)
expression(p) <- OP expression(max){n} expression(p)
                                                   (if OP is is n+1-ary prefix prec p)
expression(p) <- expression(p) OP expression(p+1)  (if OP is infixl prec p)
expression(p) <- expression(p+1) OP expression(p)  (if OP is infixr prec p)
expression(p) <- c X(lits, p)  where               (if notation := (c: p) lits)
  X((c: p) lits, q) = c X(lits, q)
  X(v (c: p) lits, q) = expression(p+1) X((c: p) lits, q)
  X(v1 v2 lits, q) = expression(max) X(v2 lits, q)
  X(v, q) = expression(q)
  X([], q) = []

Could you please say each line in english words, please ? It would help me a lot writting a correct parser.

does 
expression(p) <- OP expression(max){n} expression(p)
                                                   (if OP is is n+1-ary prefix prec p)
mean that we parse n arguments with minimum precedence max and we parse the last one with minimum precedence p, which is given by the precedence level of the 'prefix'-statement  ?

**Comment by digama0** [comment]
Regarding variables vs terms: I recently noticed that `mm0-hs` and `mm0-rs` differ in their handling of this, so I tightened up the rules to make it clearer. Terms are not allowed to share a name, and variables cannot share names with each other, but variables can share names with terms. In a statement with a variable and a term of the same name, the term is considered shadowed by the variable, and cannot be used, even if the term is referred to indirectly via a notation.

For expression parsing, you may want to consult the [mm0-hs parser](https://github.com/digama0/mm0/blob/master/mm0-hs/src/MM0/Compiler/MathParser.hs) or the [mm0-rs parser](https://github.com/digama0/mm0/blob/master/mm0-rs/src/elab/math_parser.rs) for a more executable version of the spec.

> does
> expression(p) <- OP expression(max){n} expression(p)
> (if OP is is n+1-ary prefix prec p)
> mean that we parse n arguments with minimum precedence max and we parse the last one with minimum precedence p, which is given by the precedence level of the 'prefix'-statement ?

Yes, that's correct. Precedence max means that you can only have an atomic symbol or a parenthesized expression. So for example, if `FOO a b c` is declared as `prefix foo: $FOO$ prec 50`, then the entire expression is allowed to appear at precedence <= 50, and it parses the token `FOO`, followed by two expressions at precedence `max` (for `a` and `b`), followed by an expression at precedence 50. That means that if `+` has precedence 70, then `FOO x y x + x`  parses as `FOO x y (x + x)`, `FOO x + y z w`  fails to parse, and `FOO (x + y) z w` parses as marked.

> Could you please say each line in english words, please ? It would help me a lot writting a correct parser.
> 
> expression(p1) <- expression(p2) (if p1 < p2)

An expression at a higher precedence p2 is always allowed in a lower precedence context.

> expression(max) <- '(' expression(0) ')'

Parentheses are used to put low precedence expressions in high precedence contexts.

> expression(max) <- VAR (if VAR is a variable in scope)

An atomic identifier like `x` can be used if it is a local variable. (In the existing parsers, checking that VAR is in scope happens after parsing; you can just parse something that looks like an identifier and check it later.)

> expression(1024) <- FUNC expression(max){n} (if FUNC is an n-ary term constructor)

(This clause needs to additionally say that FUNC is not a variable in scope.) An "application expression" looks like `foo e1 ... en` where `foo` is a term or def with `n` arguments. The application itself lives at precedence 1024, and the arguments are parsed at maximum precedence (so parentheses are required for non-atomic expressions). No notation need be declared to permit these expressions. This is the most common form found in `from-mm` output, because it doesn't use notations.

> expression(p) <- OP expression(max){n} expression(p)
> (if OP is is n+1-ary prefix prec p)

If a term constructor is declared with a `prefix` notation with precedence `p`, then it has a similar structure to application expressions, but the first argument is the given token instead of the name of the constructor, and the last argument to the prefix expression is parsed at precedence `p` instead of `max`. So `FOO x y a` will parse `x` and `y` at max prec and `a` at prec `p`, given `prefix foo: $FOO$ prec p;`.

A nullary term constructor with prec p just parses the given token, i.e. `FOO`, and the production is available at prec >= p as usual.

> expression(p) <- expression(p) OP expression(p+1) (if OP is infixl prec p)
> expression(p) <- expression(p+1) OP expression(p) (if OP is infixr prec p)

An infix expression cannot have prec max, and it parses one side at a higher precedence than itself. This means that if `/\` is infixl prec 35, then `a /\ b /\ c` parses `a` at prec 35 and `b` and `c` at prec 36, and means `(a /\ b) /\ c`, while if `->` is infixr prec 25, then `a -> b -> c` parses `a` and `b` at prec 26 and `c` at prec 25 and means `a -> (b -> c)`.

> expression(p) <- c X(lits, p) where (if notation := (c: p) lits)
> X((c: p) lits, q) = c X(lits, q)
> X(v (c: p) lits, q) = expression(p+1) X((c: p) lits, q)
> X(v1 v2 lits, q) = expression(max) X(v2 lits, q)
> X(v, q) = expression(q)
> X([], q) = []

This is a recursive definition of the grammar production for a notation given the sequence of literals.

A literal is either a (constant: prec) pair, or a variable. Constants are marked with precedence because they must match other uses of the same constant, but for the purpose of the grammar, it is variables that need to be marked with precedences so we can recurse. The idea is that a variable gets parsed at a precedence one higher than the precedence marked on the constant just to the right of it. If there is a variable on the right, it gets max precedence, and if it is the last variable then it gets the precedence of the leading constant, which is the same as the overall precedence of the production.

For example, the expression

     notation foo (a b c d e) := ($X$: 20) a b ($Y$: 50) c ($Z$:0) d e;

contributes a production that looks like this:

     expr(20) <- 'X' expr(max) expr(51) 'Y' expr(1) 'Z' expr(max) expr(20)

which means that an expression `X a b Y c Z d e` parses `a` at prec max, `b` at prec 51, `c` at prec 1, `d` at prec max, and `e` at prec 20, and the whole expression is only valid at prec <= 20.
