### ISSUE TITLE
confusion about definitions

### ISSUE THREAD

**Issue by Lakedaemon** [digama0/mm0#14]
what does this mean : 
If the definition part is omitted, then the existence of a definition satisfying the theorems is asserted.

What are the use cases ?
How is it used ?
How does definition unfolding happen for that case ( if it is possible) ?

**Comment by digama0** [comment]
It is used in mm0 files to indicate that a definition should be provided in the proof file. In the proof file, abstract defs are not allowed, and since definition unfolding only occurs in proofs there is nothing to worry about. The point is that in a `.mm0` file you can write `def foo (a b: nat): nat;` without providing a definition, and then in the corresponding `.mmu` file the definition will be provided (and you can unfold using that definition).
