### ISSUE TITLE
mm0-hs error verifying/lean-ifying peano example

### ISSUE THREAD

**Issue by ammkrn** [digama0/mm0#15]
commit : master 7eacd8
OS : Ubuntu 18.04.4 LTS
haskell stack : 2.1.3 (df6d1f)

I built mm0-hs using the stack install instructions. 

1 of 2:
running `mm0-hs verify peano.mm0 peano.mmu` returns:
```
spec checked
incorrect step 'axiom ax_mp', found SDecl "ax_mp" (DAxiom [(ph: wff),(ps: wff)] [im ph ps,ph] ps)
```

2 of 2:
running `mm0-hs to-lean peano.mmu -o $HOME/my_output.lean`returns:
```
mm0-hs: invalid :unfold [Atom "an",List [Atom "a",Atom "b"],List [Atom "not",List [Atom "im",Atom "a",List [Atom "not",Atom "b"]]]]
CallStack (from HasCallStack):
  error, called at src/MM0/FrontEnd/ProofTextParser.hs:32:42 in main:MM0.FrontEnd.ProofTextParser
```

The other files in the examples folder seem to work okay (they don't return errors).

**Comment by digama0** [comment]
Part 1 of 2 is fixed in 6082441 (and the 3 previous commits).

Part 2 of 2 is fixed as well now that mmu files aren't broken, although the actual lean file that is generated has a number of issues which required manual edits to fix. Things I saw:

* The variable `_G` got rendered as `«G»` which collided with another `G` in the context
* MM0 allows sorts and terms to have overlapping names, lean doesn't. In peano.mm1 there is a sort `nat` and a function `nat`, and these should be disambiguated in the lean.
* The autogenerated file should put `noncomputable theory` at the top so that it doesn't complain about defs depending on constants.
* `if` is a keyword in lean, so it should be french quoted in the output.

After fixing these issues by find and replace, the resulting lean file checks without error. I will deal with the lean output errors in another issue.

**Comment by ammkrn** [comment]
On commit ..6e7131 (master)

The `peano.mmu` file in the examples folder and the one produced by
```
mm0-rs compile peano.mm1 alt_peano.mmu
```

are different. `mm0-hs verify peano.mmu alt_peano.mmu` returns the same error as in the original issue : 
```
incorrect step 'axiom ax_mp', found SDecl "ax_mp" (DAxiom [(ph: wff),(ps: wff)] [im ph ps,ph] ps)
```

**Comment by digama0** [comment]
Master commit is not 6e7131, it is 6082441 (as of 12 days ago). On the latest master build, `peano.mmu` appears to be up to date with the result of `mm0-rs compile peano.mm1`, and `mm0-hs verify peano.mm0 peano.mmu` works.

**Comment by ammkrn** [comment]
It's 6082441, sorry. I was referring to the commit has by the suffix not the prefix (tax forms on the brain, last four of your social, etc.).

**Comment by digama0** [comment]
My claim stands. Could you show a diff demonstrating some lines that differ? That might give some clue what's going on.

**Comment by ammkrn** [comment]
Sorry, false alarm. I've been jumping around between components and I think I just forgot to rebuild mm0-rs after pulling the newest commit. Seems to be fine.
