### ISSUE TITLE
mm0-rs server panics with non-English characters

### ISSUE THREAD

**Issue by ammkrn** [digama0/mm0#25]
I'm on fa0b8b; this happens on Mac and Ubuntu 18.04. I mostly felt this was issue worthy since it's also triggered by text in comments, where it's not unreasonable that users might want to use something other than English.

I accidentally left my keyboard in a different input mode when switching back to VScode and input the character `お`. The next time I hit enter, mm0-rs panics with the following output :

```
thread 'main' panicked at 'byte index 4 is not a char boundary; it is inside 'お' (bytes 3..6) of `-- お

do {
  (def (x) 10)
};


`', /Users/ammkrn_/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/str/mod.rs:2667:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ThreadId(1): 4268ms] change do-block.mm1
```

The panic causes the server to become unresponsive until VScode is restarted. I couldn't figure out how to run the server in debug mode so that's all I have for now.

**Comment by digama0** [comment]
MM0 does not support unicode. MM1 might someday, although it will have to go though a mangling process during compilation. So I would say that for the forseeable future the correct behavior here is for the text to be rejected as a lexing error.

To recover the server if it crashes like this, remove the source of the error (the `お`) and then select the "MM0: Restart" command. You shouldn't have to restart vscode.

**Comment by ammkrn** [comment]
Thanks. I agree that just rejecting it as a lexing error is reasonable. 
Using "MM0: Restart" from the command palette doesn't seem to work as intended on VScode 1.46.1 (on both platforms). When I delete the offending character and select "MM0: Restart", the "metamath zero server" option in the tasks dropdown menu disappears, and the output console still doesn't update. The interactive elements like the underlines showing print values also disappear.

**Comment by digama0** [comment]
Oh, that's unexpected. One issue that sometimes comes up is that when the source text causes the server to crash, vscode will restart it automatically, leading to a quick sequence of crashes followed by vscode learning that the server should not be restarted because it keeps crashing, after which point it may be difficult to restart. I don't know if that's the issue you are seeing here, but I will investigate.

**Comment by digama0** [comment]
It looks like the reason the server becomes unresponsive is that although it successfully catches the panic (what you are seeing is not the usual panic report prior to an exit, it is deliberately printed after a thread dies and the server recovers), but because the thread that died was holding the lock for the active text (in the middle of calculating the result of the update to the text area, no less), the server is left in an inconsistent state on that file's contents, and is out of sync with the client until the connection is restarted. We could try to restore state by looking at the on disk contents, but if the file has unsaved changes this will not be correct. (You can actually continue to get info on unrelated files, it is just the file with the error that is permanently messed up.)

**Comment by ammkrn** [comment]
Thanks! I appreciate you taking the time to investigate (and provide a fix for) this.
