### ISSUE TITLE
Hover output sometimes unfolds defs

### ISSUE THREAD

**Issue by ammkrn** [digama0/mm0#37]
This is just a polish thing, but in certain cases the info displayed when you hover over an applied theorem shows the unfolded version of a definition even if the folded def is used in the type. This statement isn't in peano.mm1, but if you put it under `ifp` and hover over `bior2`:
```
theorem h3 : $ ~(~p /\ b) -> (ifp p a b <-> (p /\ a)) $ = '(bior2);
```
you'll see `$ ~(~p /\ b) -> (p /\ a \/ ~p /\ b <-> p /\ a) $` as the type. I think this is contextual, since in the theorem `ifppos`, hovering over `syl` will use `ifp p a b`, but hovering over the `bior2` right next to it will show the unfolded version.

**Comment by digama0** [comment]
That's not incorrect; the problem is that there are two theorem nodes at the same location, because the elaborated proof is basically `:cong ...conversion... (bior2 ...args...)`, where the top level `:cong` is a proof of `~(~p /\ b) -> (ifp p a b <-> (p /\ a))` and the `bior2` is a proof of `~(~p /\ b) -> (p /\ a \/ ~p /\ b <-> p /\ a)`, and `...conversion...` is the definition unfolding proof showing that these are the same. However MM1 has no explicit syntax for the `:cong` in refine proofs, and instead just uses type ascription to determine when they need to be automatically inserted. (It's similar to the way lean inserts `\u` coercions in terms.) So the rule it currently uses is to print the innermost proof node, which is to say when you hover over `bior2` you will see a proof that is a substitution instance of `bior2`, with the reasoning that since `bior2`'s type is printed as well, you can verify that it is actually a substitution instance more easily. We could print both theorem nodes on hover, in which case it would say that the `bior2` has both types.

**Comment by ammkrn** [comment]
> the top level `:conv` is a proof of `~(~p /\ b) -> (ifp p a b <-> (p /\ a))` and the `bior2` is a proof of `~(~p /\ b) -> (p /\ a \/ ~p /\ b <-> p /\ a)`, and `...conversion...` is the definition unfolding proof showing that these are the same. 

Since you have data showing that the folded and unfolded ones are the same, is there any way to check whether the conclusion of one is identical to what the user actually wrote when deciding what to display, or is that part of what's lost by not having the explicit `:conv`?

**Comment by digama0** [comment]
The `:conv` is there in the elaborated proof term, it just isn't written by the user and hence isn't present in the text for a useful hover. One way to get more hovers is to insert a `id @` at the beginning of the proof (or better yet, `theorem idi (h: $ a $): $ a $ = 'h;` which isn't in peano because it's pretty useless otherwise).

**Comment by ammkrn** [comment]
Ok thanks. I clearly don't know enough about these parts yet, I might come back to this later. I understand that it's not incorrect, the motivation is just that it's harder to understand the output if you have to reify the definitions in your head while reading.

**Comment by digama0** [comment]
I will see if I can set things up so that you get both hovers on the same spot. Hopefully that won't be too confusing.
