### ISSUE TITLE
How do I use the VS Code extension?

### ISSUE THREAD

**Issue by JuhoKupiainen** [digama0/mm0#4]
Not sure if this is a problem with the extension or my ability to use it..
https://stackoverflow.com/questions/59345080/how-do-i-build-an-existing-vs-code-extension

**Comment by bjorn3** [comment]
Based on another vscode ext, I think you can run:

```
$ npm install
$ ./node_modules/vsce/out/vsce package
```

to get a .vsix file you can install.

**Comment by digama0** [comment]
The way I've been installing it so far is to open the `mm0-vscode` folder in vscode, then hit F5 to build it (which will run a debug version of the extension), then copy or symlink the entire `mm0-vscode` folder into the `~/.vscode/extensions/` folder.

That said, the VSCode extension is pretty stable at this point since all the activity is in the LSP implementations, so I will look into publishing the extension so that you can just use the regular marketplace to get the extension.

**Comment by digama0** [comment]
The extension is now on the VSCode marketplace.
