### ISSUE TITLE
README.md: Elaboration of "it is possible for Metamath proofs to derive a contradiction"

### ISSUE THREAD

**Issue by void4** [digama0/mm0#41]
> Proof expressions in Metamath are strings of symbols, not trees. This is good for verification speed because computers can handle strings well, but it means that if the input expression grammar is ambiguous (and Metamath does not check this), then it is possible for proofs to take advantage of this and possibly derive a contradiction. (So one can view this as a kind of analogue to C "undefined behavior" in that the verifier is not checking this condition but needs it for the intended model to work.)

Could you please elaborate on this, maybe give an example where this would be the case?

If I built a site that automatically checked and rewarded metamath proofs of conjectures, could it be cheated this way?

**Comment by digama0** [comment]
Sure. Suppose that I have defined propositional logic with `an $a wff ph /\ ps $.` and `or $a wff ph \/ ps $.` and you forgot the parentheses, making the grammar ambiguous. (Suppose also that the usual rules of logic on and/or have been defined as axioms or theorems.) Then you can derive false like so:

    1:true-intro        |- T
    2:1:or-left-intro   |- T \/ F /\ F
    3:2:and-right-elim  |- F

The core of the trick here is that step 2 and step 3 disagree about the parse of the statement at step 2. Step 2 used an instantiation of `a |- a \/ b` with `a = T` and `b = F /\ F`, while step 3 used an instantiation of `a /\ b |- b` with `a = T \/ F`. So while step 2 morally produced the statement `T \/ (F /\ F)` and step 3 consumed the statement `(T /\ F) \/ F`, the communication between the two steps goes via the statement `|- T /\ F \/ F`, which in metamath is an actual string of tokens `T`, `/\`, `F`, `\/`, `F` and has no "memory" of which parse tree it is supposed to represent.

Now this isn't itself a huge problem, and it is common knowledge in the metamath community, but it means that grammar unambiguity is actually correctness-critical, which might be surprising to an outsider. In practice, real databases like [set.mm](https://github.com/metamath/set.mm/) overcompensate by using copious parentheses to [ensure unambiguity](http://us.metamath.org/downloads/grammar-ambiguity.txt). In particular, in set.mm 'and' and 'or' are defined as `wa $a wff ( ph /\ ps ) $.` where the parentheses (and spaces around the parentheses) are required.

From a formal perspective, this isn't especially worrisome because syntax axioms are *axioms*, so the verifier is under no obligation to provide a proof that they cohere with everything else. But getting to your second question, this tendency of metamath to mark anything it doesn't know how to check as an axiom leads to some serious limitations when it comes to the "conjecture bounty" use case. It's pretty obvious that you shouldn't let users add axioms, but in metamath you can't make a new definition without writing an axiom (a syntax axiom for the new symbol plus a logical axiom for the definition), and this means that if you fix the axioms in advance then you would be hobbled because you can't make definitions.

MM0 lifts that restriction by adding definition-making to the kernel. With the ability to create new definitions you can get pretty far in making nontrivial developments that have zero new axioms over the foundations. You still need axioms to create new sorts, so it's not quite as expressive as HOL in that regard, and the presumption is that you have relatively few sorts and do the more interesting typing at the logic level.

**Comment by void4** [comment]
Thank you very much, this was a very intuitive explanation!

A while ago I asked the following question on the math stackexchange: https://math.stackexchange.com/questions/3285084/can-all-math-expressions-be-converted-into-trees - it's kinda funny that I encounter it again in this form :)

Both this and the axiom-definition split are now reasons why I will take a closer look at MM0!
