### ISSUE TITLE
Licenses of sub-projects

### ISSUE THREAD

**Issue by Aeledfyr** [digama0/mm0#43]
In your implementation of `mm0-rs`, you have an adaptation of the `deepsize` crate.  I'm all for this, and it seems that you've made large improvements to it, but I would recommend that you  include the original copyright notice and license with it, as (I believe) is required by [`deepsize`'s license](https://github.com/Aeledfyr/deepsize/blob/master/LICENSE).

Also, I have fixed some potentially unsound code with the reference counting tracking that you may want to update here;  in the `Context`'s methods,
```rust
let pointer: usize = unsafe { *(arc as *const Arc<T> as *const usize) };
```
should be replaced with
```rust
let pointer = &**arc as *const T as *const u8 as usize;
```
(with some minor adjustments for `Rc` as well.)

**Comment by digama0** [comment]
I've added a copyright notice and transplanted the LICENSE file; see if that meets your requirements.

As for the `Arc` traversal code, I'm curious what made you change your mind on this line, as the original line contains the following:
```rust
        // Somewhat unsafe way of getting a pointer to the inner `RcBox`
        // object without changing the count
        let pointer: usize = unsafe { *(rc as *const Rc<T> as *const usize) };
```
and to the best of my understanding the comment is correct. In my code, at the point the traversal gets called, the data structure is not safe for any writes because there are concurrent readers, and this includes the reference counts, so using `deref()` as normal would actually cause a data race. Did you find another reason for this line to cause UB?

**Comment by Aeledfyr** [comment]
Looks good to me. :+1: 

The reason the line is potentially undefined is that the `Arc` and `Rc` structures are not `#[repr(C)]`, so I don't think its internal structure is stable.  The `deref` for `Arc`/`Rc` should not change the reference count, and shouldn't have to do any additional work;  The work is only done on `Arc::clone` for an increment and on `Arc::drop`, where it decrements the count and potentially frees the allocation.

The main reason is that I don't think that dereferencing an `Arc` can fail or modify the reference counts;  using deref makes this tracking possible without any unsafe code, so it should be free from data races.

**Comment by digama0** [comment]
Aha, you're right. I'll do that then.
