### ISSUE TITLE
deep recursion in letrec doesn't terminate with failure

### ISSUE THREAD

**Issue by ammkrn** [digama0/mm0#44]
I'm using 3a18fc5

A recursive function that would otherwise fail with a stack overflow error seems to loop if written using `letrec`. The mm0-rs process stays alive and continues to consume resources if you shutdown/restart the server through vscode. This example is sort of "If it hurts when you do X, stop doing X", but as an mwe:

```
(letrec ([(count x) (if (= x 0) 0 (+ 1 (count (- x 1))))]) (count 339)) -- OK
(letrec ([(count x) (if (= x 0) 0 (+ 1 (count (- x 1))))]) (count 340)) -- not OK
```

I can take a closer look at this in a few weeks if you want to put it on the backburner, but I haven't had a chance to look at the IR/lisp evaluation stuff properly yet.

**Comment by digama0** [comment]
Just in case you weren't aware, the language supports tail recursion, so it should be possible to write long loops without a stack overflow.

Also, the language currently has issues cleaning up its garbage when it comes to `letrec`, which uses mutable cells internally to create a cycle, which don't play well with the `Rc` type being used elsewhere. I tried installing a `Gc` type but it didn't go well, so this is probably a source of memory leakage. There also appears to be a bigger memory leak somewhere that I haven't identified yet, so I've usually got my fingers on the `MM0: Restart` button.

But a large stack on its own should not cause a problem; indeed a lot of functions recurse on terms and MM0 terms can be quite deeply nested, so 340 looks a little low. Evaluation uses a `Vec<Stack>` for the call stack, so since that is heap allocated it should be able to grow until it exhausts the host machine resources before failing.

An alternative to using `letrec` for recursive functions is global items, which recurse by accessing themselves through the global context and so don't cause an Rc cycle:
```
  (def (count x) (if (= x 0) 0 (+ 1 (count (- x 1)))))
  (count 340)
```
Testing this now, this causes a stack overflow but a regular one that reports the error (not very well).

**Comment by digama0** [comment]
Looking closer at the code, it appears a stack limit of 1024 (note that 1024 = 340 * 3 + 4, where the three elements for each call are the `if`, `1 + _` and return continuations) is deliberately imposed. That should probably be removed or made configurable; having a low stack limit most of the time is good for quickly catching infinite recursion before it kills your computer, but many real uses will clock in higher than that. So the letrec bug is probably pretty easy to fix; the error is somehow not getting reported properly.

**Comment by ammkrn** [comment]
Thanks for taking a look.

I did notice that recursive functions using either an accumulator or ref mutability instead of relying on thunks didn't have any stack growth issues, so I figured there was some sort of tail call support (which is much appreciated).

**Comment by digama0** [comment]
The stack limit commit 4729787 wasn't intended to fix this issue, but it inadvertently did. I think the reason for the hang was the debug printing of `self.ctx` after `stack overflow:`; because `letrec` introduces a pointer cycle, the debug printer loops forever chasing the cycle.

**Comment by digama0** [comment]
Also BTW, I notice you aren't using infix syntax for infix functions. 10/10, would recommend.
```
(letrec ([(count x) (if {x = 0} 0 {1 + (count {x - 1})})]) (count 339))
```
