### ISSUE TITLE
Bug: Extra unrelated documentation when hovering over quotes with implicit ax_mp

### ISSUE THREAD

**Issue by ml-2** [digama0/mm0#58]
When syntax_docs are enabled, when hovering over the quote of a proof, if the proof inside the quotes contains an implicit ax_mp, then the quote will give extra unrelated documentation. Right now when I do it, it gives the documentation for `:verb` in addition to the documentation for `quote`.

To quickly find an example, search for eqid in peano.mm1, and hover over the quote before its proof. It has documentation for `:verb` underneath the `quote` documentation. Then try the following alternate proof of eqid, where all the ax_mp are made explicit. This alternate proof does not have the extra documentation. Removing either ax_mp in the alternate proof makes the problem return.

```
theorem eqidALT: $ a = a $ = '(ax_mp (!! eex x (ax_mp imidm ax_7)) ax_6);
```

Other easy examples are the 3 theorems just above eqid, that is, `alimi`, `iald`, and `eex`. `iald` is the only of the three not to have this problem, and you can fix the other two using these alternate proofs:

```
theorem alimiALT (a b: wff x) (h: $ a -> b $): $ A. x a -> A. x b $ = '(ax_mp ax_4 (ax_gen h));
theorem eexALT (a: wff x) (b: wff) (h: $ a -> b $): $ ( E. x a ) -> b $ = '(ax_mp con1 @ iald @ ax_mp con3 h);
```

I'm not sure what's the source of the bug. However I have some potentially useful information for narrowing it down: I noticed that this bug was present in the commit before my pull request yesterday (specifically, 97e6bb4da8a880f9f38df8ba3a9412ec5be1c017). That commit was before the documentation for `:verb` was added, so instead the extra unrelated documentation was the info of one of the implicit ax_mp of the call. Note that in this earlier commit, this bug was present even when SYNTAX_DOCS was disabled, but now it's only present when syntax_docs is enabled.

Here's the extra documentation I get using the earlier commit when I hover over eqid's quote:

```
axiom ax_mp (a b: wff): $ a -> b $ > $ a $ > $ b $;
$ (x = a -> x = a -> a = a) -> x = a -> a = a $ >
$ x = a -> x = a -> a = a $ >
$ x = a -> a = a $
Modus ponens: from a -> b and a, infer b.
```

Which is the same as what I get when I hover over the second ax_mp in eqidALT.

---

I might try to fix it this weekend, assuming it's not already fixed by then :)

**Comment by digama0** [comment]
Most likely, the use of `:verb` comes from `refine-extra-args` which is called whenever an expression is provided more assumptions than it is supposed to receive. In the case of the eqid proof,
```
theorem eqid: $ a = a $ = '(!! eex x (imidm ax_7) ax_6);
```
`eex` takes one bound variable and one subproof, so the `ax_6` is one too many argument. In this case, MM1 calls the `refine-extra-args` callback, and peano.mm1 overrides this so that the meaning of an expression with too many arguments is to apply `ax_mp` on the extra ones. If I insert `dbg` into `refine-extra-args` like so:
```
  (def (refine-extra-args refine tgt e . ps)
    @ refine tgt @ dbg (foldl ps (verb e) @ fn (acc p2) @ copy-span e '(ax_mp ,acc ,p2)))
```
(or for a slightly nicer presentation)
```
  (def (refine-extra-args refine tgt e . ps)
    (def x (foldl ps (verb e) @ fn (acc p2) @ copy-span e '(ax_mp ,acc ,p2)))
    (display @ pp x)
    (refine tgt x))
```
you will see info on every use of `refine-extra-args` showing what the refine script was, and for the `eqid` proof it gets called twice:
```
refine '(ax_mp (:verb (imidm ?d ?e)) ax_7)
refine '(ax_mp
  (:verb
    (eex x (?a = ?b) (?b = ?b)
      (ax_mp (?a = ?b -> ?a = ?b -> ?b = ?b) (?a = ?b -> ?b = ?b)
        (imidm (?a = ?b) (?b = ?b))
        (ax_7 ?a ?b ?b))))
  ax_6)
```
These calls to `refine` ultimately end up adding syntax hints for these expressions, even though they were not written by the user directly.

The `:verb` is inserted by the `(verb e)` function, which takes care to copy the original span of its input:
```
(def (verb e) (copy-span e (list ':verb e)))
```
The purpose of `copy-span` is to create an expression as if it were written at a particular position, exactly for the reason of error reporting and hovers. However I see here that the `:verb` token itself is not re-spanned, which means it will retain the span it gets here, line 42 of peano.mm1. Once upon a time this would mean that the span actually gets reported as such, meaning that adding a new theorem can cause an error up at the top of the file, which was confusing, so now it checks when a span is way out of place and suppresses those.

However, for errors, we need some span to report the error, and I think this is due to misuse of `try_get_span` in that last commit; this defaults to the span of the whole expression, resulting in the `:verb` getting reported on the first character of the proof. I'll update it to just discard the span if it's out of range.

**Comment by ml-2** [comment]
I'd been wondering about how the implicit ax_mp worked, thanks for the explanation.

**Comment by digama0** [comment]
If you would like another thing to work on this weekend, see if you can add syntax docs to names of hard coded callbacks: `annotate`, `refine-extra-args`, and `to-expr-fallback`.

**Comment by ml-2** [comment]
Thanks, I'll look into it, that's a decent thing to work on.
