### ISSUE TITLE
MM0 docgen styling

### ISSUE THREAD

**Issue by digama0** [digama0/mm0#59]
We have a docgen now! Unfortunately, it has no style sheet so it looks pretty terrible. The resulting pages can be found at https://digama0.github.io/mm0/peano/ for now. If there are any amateur graphic designers in the house, I would be much appreciative if we got a nice modern looking web site design. I'm toying with ways to use JS to power more interactive features, including possibly the full theorem prover in the browser, but for now it's just a static site fashioned to be vaguely similar to the metamath web pages.

**Comment by ammkrn** [comment]
In implementing the rustdoc thing where major syntactic items have their own colors (functions are gold, traits are purple, ...) I noticed that you're currently using display/EnvDisplay for sorts and terms, so it's harder to embellish those since they come back as a complete string. 
Are you down with the idea of adding a third 'extra args' formatter ala EnvDisplay/EnvDebug for creating decorated html out of declarations?

**Comment by digama0** [comment]
The `Display` impl on sorts and terms delegates pretty quickly to the pretty module, which needs to be beefed up to support this. I recall that `RefDoc` has an extra type argument that I'm setting to (), which does "annotations". I think it's possible to use that for tag begin/end in order to support syntax highlighting and embedded links in the pretty result, but I haven't investigated thoroughly yet.

**Comment by ammkrn** [comment]
[this branch](https://github.com/ammkrn/mm0/tree/annot) hooks up the pretty crate's annotation feature to the existing mm0 pretty printer, and there's a macro that generates an enum for HTML tag annotations. The adjustments to the pretty module are due to the fact that the annotation type is no longer fixed as `()`. The tests in `annot` show how it's used.

The idea I went for is sort of like Visit/Fold from the syn crate, where IsAnnotation implements functions that are always called by stuff in `..lisp::pretty`, but the default trait implementations don't do anything, and annotations are only added if the annotation type calls for it.

wrt the pretty crate, if you want to keep the option of adding annotations that can't be expressed as text (like in the crate examples they show setting/clearing terminal colors) then the extra complexity of the crate's annotation feature seems warranted, but if know you're only going to annotate with things that can be expressed as text, the annotation feature doesn't do anything extra. It would be simpler to just 'annotate' by conditionally adding zero or more pp docs based on type/run-time information that tells you how to annotate.

**Comment by digama0** [comment]
> wrt the pretty crate, if you want to keep the option of adding annotations that can't be expressed as text (like in the crate examples they show setting/clearing terminal colors) then the extra complexity of the crate's annotation feature seems warranted, but if know you're only going to annotate with things that can be expressed as text, the annotation feature doesn't do anything extra. It would be simpler to just 'annotate' by conditionally adding zero or more pp docs based on type/run-time information that tells you how to annotate.

I'm not sure I understand what you mean. Annotations have to be placed inside the `Doc` as explicit nodes, because otherwise we lose track of them during layout. Once layout is complete, we can print them out by using a custom wrapped printer, as you have done, but it's not clear what beyond this the annotations feature in `pretty` does that you think is unnecessary.

It's a shame that we lose the constants `NIL`, `HARDLINE` etc. I tried using associated constants but it doesn't lift the temporaries correctly, and associated statics are not supported.

**Comment by ammkrn** [comment]
> Annotations have to be placed inside the `Doc` as explicit nodes, because otherwise we lose track of them during layout. Once layout is complete, we can print them out by using a custom wrapped printer, as you have done, but it's not clear what beyond this the annotations feature in `pretty` does that you think is unnecessary.

For any of the annotation functions (for example `ann_sort_mods`) if you kept the version that did nothing for regular printing, and the other one was implemented so that it just put the tags directly into the Doc instead of storing them as annotations which then have to be managed. You wouldn't have to use any of the annotation machinery:

```
  fn ann_sort_mods<'a>(p: &'a Pretty<'a, Self>, mods: &Modifiers) -> RefDoc<'a, Self> {
    let tag = HtmlTag::pre("sortmod");
    let mut doc = p.alloc(Doc::text(tag.open()));
    doc = p.append_doc(doc, p.alloc(Doc::text(mods.to_string())));
    p.append_doc(doc, p.alloc(Doc::text(tag.close())))
  }
```

> It's a shame that we lose the constants NIL, HARDLINE etc. 

On the bright side, it makes the module (almost) unsafe free.

**Comment by digama0** [comment]
That doesn't work, because if you put an actual text node in the pretty printer it will affect layout (the line will get used up faster than it should). Also, the writer needs additional logic to do HTML escaping, so it seems logical to put that in `AnnotWriter`.

I think this can be simplified so that the annotation is a fixed type, an enum with annotation info similar to `ObjectKind`, and the choice of how to print is simply whether we use the default writer or an HTML writer.

**Comment by ammkrn** [comment]
My bad, I didn't mean to make you do it yourself. I worked on it last night, but I should have communicated better.

**Comment by digama0** [comment]
Yeah I saw the additions after I had already built the current version. I think it differs somewhat from what you were envisioning so I think it was a useful exercise. Plus there is still a bunch more work to be done to roll out the annotations to everything else, most importantly adding links to uses of a notation. I'm not sure exactly how much marking up should be done, perhaps it's best to start with the things we can use immediately, like marking/coloring variable uses and linking definitions.

**Comment by ammkrn** [comment]
Working off your enum suggestion, I ended up doing basically the same thing you went with but I didn't push it; I agree that's a better way of doing it.

Congrats on pushing over a million lines btw (kind of a perverse statistic, but it seems fun).

**Comment by digama0** [comment]
Lol I'm sure half of that is in `node_modules`

**Comment by digama0** [comment]
My number of deleted lines just jumped from 500000 to 900000, so apparently the `docs/` folder containing the website build is actually pretty big.

**Comment by digama0** [comment]
While more improvements to the docs are welcome, we have a stylesheet now that works pretty well so I will mark this one as completed.
