### ISSUE TITLE
Proof file syntax formalization and more questions

### ISSUE THREAD

**Issue by void4** [digama0/mm0#64]
I'm fascinated by the conjecture bounty use case, and since MM0 seems to be the only system that could serve this purpose I'm wondering:

1. Reading the *Metamath Zero: The Cartesian Theorem Prover* paper, it seems that you have thought about this use case before, could you please elaborate on this? The fact that this is possible, but hasn't been done before confuses me a bit but also excites me a lot, because it seems like such a futuristic yet sensible thing. This started with me wondering whether I could put the Metamath proof verifier on the Ethereum blockchain, which would have been an easy way to get both decentralized, public, correct verification as well as financial incentives combined: https://github.com/void4/notes/issues/29

More general thoughts here: https://github.com/void4/notes/issues/65

2. Do you intend to fully formalize the proof file specification and write the reference implementation in a way that supports untrusted inputs?

3. What do you think the timeline for this project will be?

4. Has anyone tried compiling the codebase to WebAssembly? Running this on the Web or other platforms would be cool.

5. For Metamath, I found [this](https://gitlab.com/void4/mmannotate/-/raw/master/prop.mm) very simple example for both syntax and logical axioms and their usage, is there something similar for MM0 ?

**Comment by digama0** [comment]
Proof bounties have been done before. I think Coq such a program for a while, or maybe Agda? I think it went defunct though. Also I believe there were some proof bounties used when outsourcing parts of the Flyspeck proof in HOL light. But all these systems have bugs and issues that can prevent the bounty process from being fully automatic - you have to receive the proof and check it carefully to ensure it is not using one of the known exploits, which I find rather unsatisfying.

> Do you intend to fully formalize the proof file specification and write the reference implementation in a way that supports untrusted inputs?

Yes. The proof file specification is already formalized, in mm0.mm0, and while the mm0-c verifier is only as good as your average inspectable small program, the goal of the project is to produce a verifier (which probably does not differ significantly from mm0-c) for x86 which is proven correct. Note that this doesn't exactly meet your constraints if you want to stick this on a blockchain, because in that case you want the program and the proof of correctness to be relative to the semantics of the language implemented on the blockchain, e.g. etherium. This seems like a good next step, but I'm only one person and I'm prioritizing x86 for the initial version.

> 3. What do you think the timeline for this project will be?

This is my PhD thesis, which I will be finishing in the spring. Originally I was hoping to have the full verifier proof done by then, but I think it is more likely that I will only make it as far as the verified compiler, which will be useful for building other verified programs, not just the MM0 verifier itself.

> 4. Has anyone tried compiling the codebase to WebAssembly? Running this on the Web or other platforms would be cool.

I literally just did that earlier this week. It's not ready for primetime yet but https://digama0.github.io/mm0/m0e/ has a running instance of mm0-rs compiled to webassembly. (It's only "running" in the sense of warming your computer though.) Once I hook up the API, you should be able to use it similar to the vscode extension.

> For Metamath, I found this very simple example for both syntax and logical axioms and their usage, is there something similar for MM0 ?

There are a few example files in the [`examples`](https://github.com/digama0/mm0/tree/master/examples) directory. [`goldbach.mm0`](https://github.com/digama0/mm0/blob/master/examples/goldbach.mm0) is pretty good to look at, as well as [`hello.mm0`](https://github.com/digama0/mm0/blob/master/examples/hello.mm0) for the more computational side of things, but I don't have an exact analogue of that file ATM.

**Comment by digama0** [comment]
> Do you intend to fully formalize the proof file specification and write the reference implementation in a way that supports untrusted inputs?

Actually, I should amend this: the *proof file* does not have an official specification; it is treated as an implementation detail of the verifier and is allowed to be verifier specific. (That said it is produced by mm0-rs and consumed by mm0-c so there is some role for clear documentation of what the format is, precisely.) The only thing that actually receives an official specification is the *proof content*, you might say the abstract version of the proof object, because this is used to define the correctness/provability relation on specification files. This is what you will find in mm0.mm0.

Basically, the spec defines a function from input specifications `s` to `Prov(s)` that asserts that `s` is a well formed specification that is provable, and the correctness condition for the verifier is that whenever the verifier returns success given input `s` (with a proof file `p` possibly being supplied via some arbitrary other channel), then `Prov(s)` holds. The verifier need not catch errors in `p`, and in fact it need not even have any such `p` - it can receive guidance by user intervention or magic or brute force, so long as if it accepts then `Prov(s)` holds.

**Comment by void4** [comment]
>you want the program and the proof of correctness to be relative to the semantics of the language implemented on the blockchain

The good news is that future versions of Ethereum will use WebAssembly instead of the EVM, old contracts will be cross compiled. It's all still a work in progress though, and may take at least a year, maybe two or more to materialize.

It also does not *have* to be Ethereum it can also be another blockchain or form of computing system, perhaps even a real legal foundation, though I'd rather prefer the properties of the former approach.

Having something that makes it possible for anyone to set rewards could have interesting implications and applications.

> This is my PhD thesis, which I will be finishing in the spring.

I wish you so much joy and success with this, because this is the most interesting project I have seen so far. I'm just a programmer with a limited understanding of (Meta)math so this might not mean much, but I feel that this one might be important.

>> Has anyone tried compiling the codebase to WebAssembly?

> I literally just did that earlier this week.

Oh my :D :100: 

I tried it for a very short while myself, but at the time there seemed to be too many dependencies that were not available in the Wasm environment. Glad to know this is possible and not prevented by the architecture!

> There are a few example files in the examples directory. goldbach.mm0 is pretty good to look at, as well as hello.mm0 for the more computational side of things, but I don't have an exact analogue of that file ATM.

Thanks! So far I've only looked very superficially at this project. The design choice of having two files (mm0+mmu/mmb) was, coming from and knowing only Metamath a bit, a bit confusing to me, but thinking about the "verify untrusted inputs" use case it makes good sense :)

> the only thing that actually receives an official specification is the proof content

It might be useful for there to be also a standardized proof file format which many tools can use, so results of the implementations of the same proof file-to-abstract spec representation process can be cross-checked.

**Comment by bjorn3** [comment]
> I tried it for a very short while myself, but at the time there seemed to be too many dependencies that were not available in the Wasm environment. Glad to know this is possible and not prevented by the architecture!

Unless you are doing architecture dependent things, it is often very easy to compile rust to wasm as most foundational crates have wasm support when possible and cargo automatically builds all rust dependencies for the target architecture when cross-compiling.

**Comment by digama0** [comment]
> The design choice of having two files (mm0+mmu/mmb) was, coming from and knowing only Metamath a bit, a bit confusing to me, but thinking about the "verify untrusted inputs" use case it makes good sense :)

Well, one thing that might strike you as odd if you try to read the actual text of set.mm is that it is only about 50% readable text, with the other half being compressed proof blocks. It's almost as if it is two files for two different kinds of reader, interspersed. MM0 just makes that division more explicit.

> It might be useful for there to be also a standardized proof file format which many tools can use, so results of the implementations of the same proof file-to-abstract spec representation process can be cross-checked.

Yes, the .mmb format is beginning to turn out that way.

@bjorn3 while I have you here, do you know whether wasm supports multithreading, or at least a message pump from another JS thread in a web worker? I'm not really sure how the rust code is supposed to get interrupted to receive a message from the host, and the JS thread can't directly poke at the WASM module AFAICT.

**Comment by bjorn3** [comment]
Multithreading requires shared memory, which was put on a halt due to spectre, meltdown and other side-channel attacks. There is now a path forward to supporting this, but it requires an http header to be set, so it likely won't work on github pages. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

I don't think there is a way to receive a message outside of the `onmessage` event handler. There is the `worker.terminate()` method to forcefully stop a webworker though in case the worker takes too long to finish. You can then simply restart it from scratch.

If you simply want a "loop" receiving new messages, the way to go would be for the rust code to export a function that the `onmessage` handler can invoke each time a new message is received. The rust code will then not run at all when there is no new message. You could for example use wasm-bindgen for this.
