### ISSUE TITLE
Default valùe for MAP_FILE

### ISSUE THREAD

**Issue by Sylvain78** [digama0/mm0#66]
Define MAP_FILE as 0 if not defined, in mm0-c

**Comment by bjorn3** [comment]
It should always exist on Linux. From the man page:

> <dl><dt>MAP_FILE</dt><dd>Compatibility flag.  Ignored.</dd></dl>

**Comment by jcommelin** [comment]
Is the accent on the `u` intentional?

**Comment by digama0** [comment]
I couldn't find any evidence that this is not always defined. On my install this is behind a `__USE_MISC` ifdef, but I think if that is not defined there will be bigger problems. It might be better to just drop the dependency on libc altogether since the final product is going to be making syscalls directly, but for now it seems best to keep things as simple as possible and not bring in too much C weirdness.

Since `MAP_FILE` is 0, it's also an option to just drop it (the gnu hurd manual mentions that it is optional, so this is probably reliable), but I would want to know more about the kind of system that might not have this first.

**Comment by bjorn3** [comment]
You can't avoid libc on pretty much any system other than Linux. Go tried, but it bit them hard. On multiple occasions it became impossible to run old go executables on new systems. For example macOS changed a detail in I think a thread system call. OpenBSD is even in the process of preventing system calls outside libc as exploit mitigation strategy.

**Comment by digama0** [comment]
Well in my case it's literally not an option to statically link to libc, because every byte that is being emitted comes with a formal proof, so this would entail formalizing all of libc, which besides being a lot of work would also reveal the "secret sauce" of the library and so we could just use that and skip the library text. It is probably possible to dynamically link to libc, if that's what it takes to run on systems like OpenBSD, but the initial version is definitely going to be "bare metal userland" programming, and all portability will be explicitly enabled by system specific interface definitions.

But that's all for the future. `mm0-c` is just a plain old POSIX program. From https://support.sas.com/documentation/onlinedoc/ccompiler/doc750/html/lr2/z2101547.htm , it looks like `MAP_FILE` is not standardized, so I'll just remove it.

**Comment by Sylvain78** [comment]
Thanks, i just forgot to mention my OS is [Haiku](https://www.haiku-os.org).
So no linux related at all.

**Comment by digama0** [comment]
@Sylvain78 I inferred that after looking at your github profile, but I couldn't find where Haiku keeps its libc. What do the relevant headers look like?
