### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by Lakedaemon** [digama0/mm0#7]
formula-arrow-type ::= formula | (type | formula) '>' arrow-type

is actually 

formula-arrow-type ::= formula | (type | formula) '>' formula-arrow-type

Because theorem a1i (ph ps: wff): $ ph $ > $ ps -> ph $;

right ?

**Comment by Lakedaemon** [comment]
Could you update the documentation about "import"

There is a statement 
`import "peano.mm0";
in peano_hex.mm0 and the grammar of .mm0 files doesn't speak at all about it.
What should we do about it ?

**Comment by digama0** [comment]
The official mm0 spec doesn't support import statements, so you should copy the contents of peano.mm0 at the location of the `import "peano.mm0";` line.

If you want to support import statements, they have the grammar `import <quoted-string>;` and act like a textual substitution, except that multiple imports of the same file are ignored (so import diamonds are possible).

**Comment by digama0** [comment]
the grammar issue is fixed in 3878cd4

**Comment by Lakedaemon** [comment]
in mm0.mm0, you use : 
theorem ProofThm (env e p a h r .p1 .ds .pf .ctx: nat):
but the grammar for theorem uses identifier or identifier_ (not dummy-identifier)

Also, I do not want to be annoying. 
What is the adequate place for : 
a) reporting issues with mm0/documentation
b) asking question about mm0, 
c) holding (public) discussion about the mm0 design with mm0's author/contributors  ?

Best regards,
Olivier

**Comment by Lakedaemon** [comment]
Also, in mm0.md, it is written that

> Warning: This spec has not yet stabilized. If you are interested in writing a verifier for this spec you 
> should stay appraised for changes to the spec.

which is fair enough. I would like to write a mm0 verifier. Is there a way I could get an email if there is a breaking/significant change in the mm0 design ?
My email is olivier dot binda at wanadoo dot fr

**Comment by digama0** [comment]
> in mm0.mm0, you use :
> theorem ProofThm (env e p a h r .p1 .ds .pf .ctx: nat):
> but the grammar for theorem uses identifier or identifier_ (not dummy-identifier)

I'm not sure what about this you are specifically calling attention to. In mm0.mm0 there is an abstract definition of the concept of a proof. It most closely corresponds to the inductive judgment rule for theorem application in the MM0 paper. It does not directly correspond to anything in the .mm0 grammar or syntax, but is used to define which specifications are provable. In particular, the theoretical presentation does not use identifiers nearly as much as the concrete syntax, and instead uses numbers, or in the case of theorems, nothing at all except the statement of the theorem. So things like identifier vs identifier_ don't come up.

> Also, I do not want to be annoying.
> What is the adequate place for :
> a) reporting issues with mm0/documentation
> b) asking question about mm0,
> c) holding (public) discussion about the mm0 design with mm0's author/contributors ?

I am perfectly happy to respond to comments and questions here, or on the metamath google group. Activity is a sign of health of the project.

If you open issues here, they will have better long term visibility, but github issues work best when the questions are clear and pointed, and answers (or a discussion leading to a conclusion) can be found. I would ask that you open a new issue for each separate topic rather than piling more questions into the same issue. There is no cost to having more issues open, even if they are small things. So I recommend github for (a).

The google group is better suited to vaguer questions, general discussion, and broader questions about the project. There are more subscribers there, so if you want to get lots of different views that's a better place to go. So (c) is probably a better fit there, and (b) could be here or there depending on the question.

> Also, in mm0.md, it is written that
> 
> > Warning: This spec has not yet stabilized. If you are interested in writing a verifier for this spec you
> > should stay appraised for changes to the spec.
> 
> which is fair enough. I would like to write a mm0 verifier. Is there a way I could get an email if there is a breaking/significant change in the mm0 design ?

At this point, it's pretty stable already. The two factors that will freeze it the most are (1) formal verification, in progress, and (2) use by people other than me. So I expect that your writing a verifier will help to pin it down more. Most changes are likely to come from issues like this one, so if you subscribe to the repo then you should see these come by. How about this: henceforth, any changes other than bugfixes to the spec will come with an issue and/or PR documenting the change. That should let you stay on top of things.

I have a request in response: MM0 is public domain, so I won't force you, but could you open-source the portion of your program that is the MM0 verifier (for example by having it as an external library)? That way, I could check my files against your verifier and send you PRs if necessary.

**Comment by digama0** [comment]
@Lakedaemon The "import" issue is addressed somewhat by commit 2defc96, which adds a command `mm0-rs join foo.mm0` that will search and replace all `import "bar.mm0";` lines with the contents of `bar.mm0` and so on recursively, producing a proper mm0 file with no import statements on stdout (which can be piped to a file, or even directly to the mm0-c verifier, which takes an mm0 file on stdin).
