### ISSUE TITLE
Translation from MM to MM0 - Example with the formalisation in MM of Matching Logic

### ISSUE THREAD

**Issue by amelieled** [digama0/mm0#93]
Hi everyone!

I originally wanted to understand how $d statements are translated into MM0, but I can't translate a simpler extract of Matching Logic formalised in MM.
That is, this extract of Matching Logic:
```
$c #Pattern #ElementVariable #SetVariable #Variable #Symbol $.
$c #ApplicationContext \app ( ) $.
$v ph0 ph1 x y X Y xX yY sg0 $.

$( Syntax $)

ph0-is-pattern   $f #Pattern ph0 $.
ph1-is-pattern   $f #Pattern ph1 $.
ph2-is-pattern   $f #Pattern ph2 $.
ph3-is-pattern   $f #Pattern ph3 $.
ph4-is-pattern   $f #Pattern ph4 $.
ph5-is-pattern   $f #Pattern ph5 $.
x-is-element-var $f #ElementVariable x $.
y-is-element-var $f #ElementVariable y $.
X-is-element-var $f #SetVariable X $.
Y-is-element-var $f #SetVariable Y $.
xX-is-var        $f #Variable xX $.
yY-is-var        $f #Variable yY $.
sg0-is-symbol    $f #Symbol sg0 $.
```
becomes:
`delimiter $ ( $ $ ) $;`
after running the following command line:
`mm0-hs from-mm tests.mm` and the result.

**Comment by digama0** [comment]
The file translates to essentially nothing because there are no actual theorems in your MM snippet.

* There is no real equivalent of `$c` statements in MM0, they translate to nothing. They are involved in the `infixl`/`prefix`/`notation` commands, but the MM equivalent needs a combination of `$c` and an `$a` syntax axiom to do the same thing.
* `$v` statements are not needed at all in MM0, they are subsumed by `$f` statements, but...
* `$f` statements at global scope don't exist in MM0. Instead, each theorem has local variable declarations, and the translation looks at the MM `$f` statements to determine the types of all the variables in a given theorem statement.

That means that unless you use a `$a` or `$p` statement, you will get nothing at all out in MM0, because you haven't asserted anything, only set up a context to maybe say something.

This also extends to `$d` and `$e` statements. These are scoped in MM, but they are still standalone statements, while in MM0 they are attached to axioms and theorems. So if you put `$d` and `$e` statements but no `$a` or `$p` then you still get no output.

But let's talk about a MM file which actually has some `$d` and `$a` statements in it (using set.mm syntax since I'm more familiar with that):

```
$c |- setvar wff $.
$v x y z ph ps $.
vx $f setvar x $.
vy $f setvar y $.
vz $f setvar z $.
wph $f wff ph $.
wps $f wff ps $.
wal $a wff A. x ph $.
wi $a wff ( ph -> ps ) $.
${
  $d x y z $.  $d ph x $.  $d ps y $.
  foo.1 $e |- ( ph -> ps ) $.
  foo $a |- A. x A. y A. z ( ph -> ps ) $.
$}
```
This corresponds to the following MM0 file:
```
term wal {x: setvar} (ph: wff x): wff;
prefix wal: $A.$ prec 20;
term wi (ph ps: wff): wff;
infixr wi: $->$ prec 25;
axiom foo {x y z: setvar} (ph: wff y z) (ps: wff x z)
  (h1: $ ph -> ps $):
  $ A. x A. y A. z ( ph -> ps ) $;
```
Some observations:
* The specific choice of precedence value `20` for `wal` and `25, right associative` for `wi` are not present in the MM file, they have to be additionally supplied. The automatic translator does not make an attempt to translate notation, so it will write all the axiom and theorem statements in s-expression form, in this case `wal x (wal y (wal z (wi ph ps)))`.
* The `$f` statements in the MM file have been used to make sure that `x: setvar` and `ph: wff` wherever they appear.
* Syntax axioms like `wal` and `wi`, that is `$a` statements whose conclusion does not start with `|-`, translate to `term` declarations.
* Regular axioms like `foo` translate to `axiom` statements in MM0.
* The `$d` statements translate to list of dependencies after regular variables, but complemented. In this case we have that `ph: wff y z` and `ps: wff x z`, which is sometimes written `ph(y, z)` in the textbooks, because `ph` is allowed to depend on `y` and `z` but not `x`; we know this from the `$d ph x $.` statement in the MM input file.
* The `$e` statements translate to hypotheses to the theorem, written as additional arguments before the colon, here `h1: $ ph -> ps $`.

**Comment by amelieled** [comment]
Thank you very much for the quick response and the very clear explanation!
I just understood a lot of things!

I have two questions:
* What is the type of `setvar`? and `wff`?
* How does MM0 differentiate between a syntax axiom and a regular axiom?
   It seems that `|-` is a special symbol (whereas MM never says that!).

**Comment by benjub** [comment]
Sorry if that was already answered, but set.mm currently contains
>  bj-0 $p wff ( ( ph -> ps ) -> ch ) $= ( wi ) ABDCD $.

I can remove it if this messes things up, but just to be sure: does it mean that if we wanted to allow this, we should write `$j syntax 'wff' as 'wff';` in addition to (or in place of?) `$j syntax 'wff';` ? And this would translate to `provable sort wff` ? Would this be problematic ? (I'm not at all advocating it, this is just out of curiosity.)

**Comment by digama0** [comment]
It is problematic, but not for the reasons you have indicated. It is okay to prove "syntax theorems", as long as they also satisfy the conditions on other syntax axioms - no repeated variables, no $d or $e assumptions - but they can interfere with unambiguous parsing, because a single expression can have multiple parse trees in the presence of theorems, in this case `wi (wi wph wps) wch` vs `bj-0 wph wps wch`. There is precedent for syntax theorems, however, since `weq` and `wel` are just that. I believe most parsers will just ignore syntax theorems.

MM0 has no grammatical space for syntax theorems. It is not something you can express in the first place, so it does not interfere with anything. Terms are identified with their syntax proofs (rather than their list of tokens as in MM).

**Comment by digama0** [comment]
That's not MM0 syntax, it is metamath $j comment syntax. But yes, `syntax 'aaa' as 'bbb'` declares `'aaa'` as a new typecode so it should not have been introduced previously with another `syntax` command, and `'bbb'` is supposed to be an already declared typecode so it follows that aaa != bbb.

**Comment by amelieled** [comment]
> I forgot to add that `setvar` and `wff` have to be declared first in MM0, like so:
> 
> ```
> sort setvar;
> provable sort wff;
> ```
> 
> So they are themselves types (MM0 uses the "sort" terminology because these are very simple kinds of types), they classify variables and expressions. So for example `wal x ph` is an expression of sort `wff` if `x: setvar` and `ph: wff ...` are in the context.

OK, so `wff` is a sort but can take arguments (and not the same number of arguments) as in `ph: wff y z` and `ps: wff x`?

**Comment by digama0** [comment]
Not exactly; that is part of the notation for variable declarations. It's basically saying `ph(y, z): wff`, that is, `ph` is an expression possibly containing free occurrences of `y` and `z`, which is a `wff`. In a type theory, you might instead use the notation `ph: setvar -> setvar -> wff`, except that you are only allowed to use `ph` applied as `ph(y, z)` instead of `ph(A, B)` for other expressions `A` and `B`. (Or rather, you write `ph` and it is interpreted to mean `ph(y, z)`.) You can use explicit quantification to get it evaluated at other values; for example if `ph: wff x` then `A e. {x | ph}` is a way to express `ph(A)` instead of `ph(x)`.

**Comment by amelieled** [comment]
OK I see, it's clear, thanks!

**Comment by amelieled** [comment]
I continue with my original problem: translating the MM formalisation of the Matching Logic into MM0:
If I add `element-var-is-var $a #Variable x $.`
I obtain: `at element-var-is-var: sort '#Variable' not declared`

**Comment by digama0** [comment]
As I mentioned, the translator requires some $j comments to declare sorts, because MM does not have enough information to determine what is a sort. Adding
```
$( $j syntax '#Variable'; $)
```
should do the job, although I forget what it does with non-identifier characters (`#` is not okay as part of a MM0 sort name).

**Comment by amelieled** [comment]
Oh my bad, I forgot this point...
But with this file:
```
$c #Pattern #ElementVariable #SetVariable #Variable #Symbol $.
$c #Positive #Negative #Fresh #ApplicationContext #Substitution #Notation |- $.
$c \bot \imp \app \exists \mu ( ) $.
$v ph0 ph1 ph2 ph3 ph4 ph5 x y X Y xX yY sg0 $.

$( Syntax $)

ph0-is-pattern   $f #Pattern ph0 $.
ph1-is-pattern   $f #Pattern ph1 $.
ph2-is-pattern   $f #Pattern ph2 $.
ph3-is-pattern   $f #Pattern ph3 $.
ph4-is-pattern   $f #Pattern ph4 $.
ph5-is-pattern   $f #Pattern ph5 $.
x-is-element-var $f #ElementVariable x $.
y-is-element-var $f #ElementVariable y $.
X-is-element-var $f #SetVariable X $.
Y-is-element-var $f #SetVariable Y $.
xX-is-var        $f #Variable xX $.
yY-is-var        $f #Variable yY $.
sg0-is-symbol    $f #Symbol sg0 $.
$( $j syntax '#Variable'; $)
element-var-is-var $a #Variable x $.
set-var-is-var     $a #Variable X $.
```
I obtain:
```
delimiter $ ( $ $ ) $;

mm0-hs: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Internal.hs:610:17 in containers-0.6.0.1:Data.Map.Internal
```
I think the problem comes from the fact that there is already this declaration:
`x-is-element-var $f #ElementVariable x $.`.

**Comment by digama0** [comment]
I don't see anything immediately wrong with your code, but `#Pattern`, `#ElementVariable`, `#SetVariable` and `#Symbol` should also be declared as `syntax`, and that might be the issue.

Note: the MM -> MM0 translator is not very robust and is only really tested on set.mm-like databases. It's past due for a rewrite as part of mm0-rs. But if you don't already have an MM database, there isn't much sense in writing one just to translate it to MM0 - the result you get from writing it directly in MM0 will be strictly better (able to use more non-MM features like notation and definitions).

**Comment by digama0** [comment]
@amelieled ac68dfb should fix the error you are seeing. Now it reports:
```
at ph0-is-pattern: '#Pattern' is not a declared sort
```
because you did not declare `$( $j syntax '#Pattern'; $)` first.

**Comment by amelieled** [comment]
Yes, thanks! :)
I can translate the entire formalization file by adding:
``` 
$( $j syntax '#Pattern'; $)
$( $j syntax '#ElementVariable'; $)
$( $j syntax '#SetVariable'; $)
$( $j syntax '#Variable'; $)
$( $j syntax '#Symbol'; $)
$( $j syntax '#Positive'; $)
$( $j syntax '#Negative'; $)
$( $j syntax '#Fresh'; $)
$( $j syntax '#ApplicationContext'; $)
$( $j syntax '#Substitution'; $)
$( $j syntax '#Notation'; $)
```
(but the translation seems partial)

One last question maybe: how are the proofs translated from MM to MM0?

**Comment by digama0** [comment]
What do you mean by partial? It should translate all the theorems, but not $c, $v, $f, $d, $e statements since these are only auxiliaries for defining axioms/theorems from MM0's perspective, they do not contribute to the logical content of the database. (It also does not translate comments, but I don't think that's what you mean.)

Proofs are translated fairly directly: each MM proof step has a corresponding MM0 proof step, and the proofs are stored in an MMU file with a lisp-like syntax for storing the proof trees. There is some complication when theorems have non-disjoint bound variables in MM (these have to be "monomorphized" into variations for all ways these variables can be equal or distinct in MM0), but otherwise it's just rule application. If you write a MM file with a $p you will see what it does.
